package com.testapp.db.testapp_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE CompanyInfoBase PLEASE EDIT ../CompanyInfo.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of CompanyInfo object
 * 
 */

import javax.persistence.GeneratedValue;
import javax.persistence.MappedSuperclass;
import javax.persistence.Id;
import javax.persistence.Column;
import java.util.Date;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.FetchType;
import java.util.stream.Collectors;

import com.testapp.db.testapp_db.entity.CompanyInfo;
// Import relations


@MappedSuperclass
public class CompanyInfoBase {
	
	@Id
	@GeneratedValue
	private Long _id;
	
	// Attributes
	@Column()
    private String Description;
	@Column()
    private String Facebook;
	@Column()
    private String HQAddress;
	@Column()
    private String LinkedIn;
	@Column()
    private String Name;
	@Column()
    private String Twitter;
	@Column()
    private String VATID;
	@Column()
    private String Website;
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getDescription() {
		return Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}
	public String getFacebook() {
		return Facebook;
	}

	public void setFacebook(String Facebook) {
		this.Facebook = Facebook;
	}
	public String getHQAddress() {
		return HQAddress;
	}

	public void setHQAddress(String HQAddress) {
		this.HQAddress = HQAddress;
	}
	public String getLinkedIn() {
		return LinkedIn;
	}

	public void setLinkedIn(String LinkedIn) {
		this.LinkedIn = LinkedIn;
	}
	public String getName() {
		return Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}
	public String getTwitter() {
		return Twitter;
	}

	public void setTwitter(String Twitter) {
		this.Twitter = Twitter;
	}
	public String getVATID() {
		return VATID;
	}

	public void setVATID(String VATID) {
		this.VATID = VATID;
	}
	public String getWebsite() {
		return Website;
	}

	public void setWebsite(String Website) {
		this.Website = Website;
	}
    

    
}