package com.testapp.db.testapp_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE CompanyInfoBaseDto PLEASE EDIT ../CompanyInfoDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of CompanyInfo object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;


import com.testapp.db.testapp_db.entity.CompanyInfo;
// Import relations

public class CompanyInfoBaseDto {
	
	private Long _id;
	
	// Attributes
    private String Description;
    private String Facebook;
    private String HQAddress;
    private String LinkedIn;
    private String Name;
    private String Twitter;
    private String VATID;
    private String Website;
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getDescription() {
		return Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}
	public String getFacebook() {
		return Facebook;
	}

	public void setFacebook(String Facebook) {
		this.Facebook = Facebook;
	}
	public String getHQAddress() {
		return HQAddress;
	}

	public void setHQAddress(String HQAddress) {
		this.HQAddress = HQAddress;
	}
	public String getLinkedIn() {
		return LinkedIn;
	}

	public void setLinkedIn(String LinkedIn) {
		this.LinkedIn = LinkedIn;
	}
	public String getName() {
		return Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}
	public String getTwitter() {
		return Twitter;
	}

	public void setTwitter(String Twitter) {
		this.Twitter = Twitter;
	}
	public String getVATID() {
		return VATID;
	}

	public void setVATID(String VATID) {
		this.VATID = VATID;
	}
	public String getWebsite() {
		return Website;
	}

	public void setWebsite(String Website) {
		this.Website = Website;
	}
    

    
}