/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE company-infoBaseService PLEASE EDIT ../company-info.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { CompanyInfo } from '../../domain/testapp_db/company-info';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../CompanyInfo.service.ts
 */

/*
 * SCHEMA DB CompanyInfo
 *
	{
		Description: {
			type: 'String'
		},
		Facebook: {
			type: 'String'
		},
		HQAddress: {
			type: 'String'
		},
		LinkedIn: {
			type: 'String'
		},
		Name: {
			type: 'String'
		},
		Twitter: {
			type: 'String'
		},
		VATID: {
			type: 'String'
		},
		Website: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class CompanyInfoBaseService {

    contextUrl: string = environment.endpoint + '/company';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * CompanyInfoService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: CompanyInfo): Observable<CompanyInfo> {
        return this.http
            .post<CompanyInfo>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * CompanyInfoService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * CompanyInfoService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<CompanyInfo> {
        return this.http
            .get<CompanyInfo>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * CompanyInfoService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<CompanyInfo[]> {
        return this.http
            .get<CompanyInfo[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * CompanyInfoService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: CompanyInfo): Observable<CompanyInfo> {
        return this.http
            .post<CompanyInfo>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
