/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE user-infoBaseService PLEASE EDIT ../user-info.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { UserInfo } from '../../domain/testapp_db/user-info';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../UserInfo.service.ts
 */

/*
 * SCHEMA DB UserInfo
 *
	{
		Address: {
			type: 'String',
			required : true
		},
		Company: {
			type: 'Boolean'
		},
		Country: {
			type: 'String',
			required : true
		},
		Firstname: {
			type: 'String'
		},
		Lastname: {
			type: 'String',
			required : true
		},
		WebsiteAddr: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class UserInfoBaseService {

    contextUrl: string = environment.endpoint + '/registrationinfo';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * UserInfoService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: UserInfo): Observable<UserInfo> {
        return this.http
            .post<UserInfo>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * UserInfoService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * UserInfoService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<UserInfo> {
        return this.http
            .get<UserInfo>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * UserInfoService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<UserInfo[]> {
        return this.http
            .get<UserInfo[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * UserInfoService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: UserInfo): Observable<UserInfo> {
        return this.http
            .post<UserInfo>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
